long double solaris cran issue
On Sparc Solaris (which does not have long doubles) this fails its
tests with

 Running ‘testExpressionAnalysis.R’ [51s/51s]
ERROR
Running the tests in ‘tests/testExpressionAnalysis.R’ failed.
Last 13 lines of output:
 --- testBaselineIntensity: PASS ALL TEST ---
 > testRollUp()
  --- testRollUp ---
                                        A_rep_1    A_rep_2    B_rep_1
 B_rep_2
                                     898931.931 898873.936 899764.708
899845.621
 [15] Phospho (ST)|[30] Phospho (ST)   1000.504   1000.923   1002.302
1001.896
 [20] Phospho (ST)                     1002.138   1000.492   1003.316
1001.913
                                        C_rep_1     C_rep_2
                                     897969.703 898040.2704
 [15] Phospho (ST)|[30] Phospho (ST)   1000.061    999.5145
 [20] Phospho (ST)                     1001.416    998.5638
 Error: sum(exprs(rollUpEset2)) == sum(exprs(rollUpEset1)) is not TRUE